[package]
name = "egui_example"
version = "0.1.0"
authors = ["Nils Hasenbanck <nils@hasenbanck.de>"]
edition = "2018"

[dependencies]
chrono = "0.4"
futures-lite = "1.11"
egui = "0.3"
egui_wgpu_backend = { version = "0.2", git = "https://github.com/hasenbanck/egui_wgpu_backend" }
egui_winit_platform = { version = "0.2", git = "https://github.com/hasenbanck/egui_winit_platform" }
wgpu = "0.6"
winit = "0.23"

[patch."https://github.com/hasenbanck/egui_wgpu_backend"]
# egui_wgpu_backend = { path = "../egui_wgpu_backend" }

[patch."https://github.com/hasenbanck/egui_winit_platform"]
# egui_winit_platform = { path = "../egui_winit_platform" }

[patch.crates-io]
egui = { version = "0.3", git = "https://github.com/emilk/egui" }
